/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as FootwearRouteImport } from './routes/footwear'
import { Route as NewInRouteImport } from './routes/new-in'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as ShopRouteImport } from './routes/shop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const FootwearRoute = FootwearRouteImport.update({
  id: '/footwear',
  path: '/footwear',
  getParentRoute: () => rootRouteImport,
} as any)
const NewInRoute = NewInRouteImport.update({
  id: '/new-in',
  path: '/new-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/footwear': typeof FootwearRoute
  '/new-in': typeof NewInRoute
  '/sale': typeof SaleRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/footwear': typeof FootwearRoute
  '/new-in': typeof NewInRoute
  '/sale': typeof SaleRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/footwear': typeof FootwearRoute
  '/new-in': typeof NewInRoute
  '/sale': typeof SaleRoute
  '/shop': typeof ShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accessories' | '/footwear' | '/new-in' | '/sale' | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accessories' | '/footwear' | '/new-in' | '/sale' | '/shop'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/footwear'
    | '/new-in'
    | '/sale'
    | '/shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  FootwearRoute: typeof FootwearRoute
  NewInRoute: typeof NewInRoute
  SaleRoute: typeof SaleRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footwear': {
      id: '/footwear'
      path: '/footwear'
      fullPath: '/footwear'
      preLoaderRoute: typeof FootwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-in': {
      id: '/new-in'
      path: '/new-in'
      fullPath: '/new-in'
      preLoaderRoute: typeof NewInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  FootwearRoute: FootwearRoute,
  NewInRoute: NewInRoute,
  SaleRoute: SaleRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
